import pygame
import sys
import math
import random
from track import Track
from car import Car

WIDTH, HEIGHT = 1920, 1080

# Colors
BLACK = (0, 0, 0)
GRAY = (150, 150, 150)
WHITE = (255, 255, 255)
CAR = (255, 0, 0)
COLORS = {'BLACK': BLACK, 'GRAY': GRAY, 'WHITE': WHITE, 'CAR': CAR}

def create_track(
    track_width: int = 60,
    seed: int | None = None,
    straights: int = 1,
    hairpins: int = 1,
    chicanes: int = 0,
    sweepers: int = 0,
    s_curves: int = 1,
    laps: int = 1,
    # sizing/shape params
    base_radius: float = 300.0,
    variance: float = 120.0,
    straight_length: float = 500.0,
    hairpin_radius: float = 90.0,
    sweeper_radius: float = 220.0,
    chicane_offset: float = 120.0,
):
    """
    Procedurally generate a closed track composed of parameterized segments.

    Parameters:
      - track_width: width of the track surface.
      - seed: RNG seed for reproducibility.
      - straights, hairpins, chicanes, sweepers, s_curves: segment counts.
      - laps: repeat the segment set N times for longer tracks.
      - base_radius, variance: overall size tuning (used in initial heading/shape jitter).
      - straight_length: nominal length for straight segments.
      - hairpin_radius, sweeper_radius, chicane_offset: curvature/offset controls.

    Notes:
      - The path is generated by integrating small steps. The closure is handled by
        Track._calculate_walls which connects end-to-start; there may be a sharp join
        if headings differ (by design for simplicity).
    """
    rng = random.Random(seed)

    # Turtle state (start around origin; we'll center/scale later)
    x, y = 0.0, 0.0
    heading = rng.uniform(0.0, 2.0 * math.pi)

    points: list[tuple[float, float]] = [(x, y)]

    # Integration step helper
    def add_straight(length: float):
        nonlocal x, y, heading
        length = max(20.0, float(length))
        steps = max(2, int(length / 8.0))
        ds = length / steps
        for _ in range(steps):
            x += ds * math.cos(heading)
            y += ds * math.sin(heading)
            points.append((x, y))

    def add_arc(radius: float, angle_deg: float, direction: int | None = None):
        nonlocal x, y, heading
        radius = max(20.0, float(radius))
        angle_rad = abs(math.radians(angle_deg))
        if angle_rad < 1e-3:
            return
        sign = rng.choice([1, -1]) if direction is None else (1 if direction > 0 else -1)
        arc_len = angle_rad * radius
        steps = max(4, int(arc_len / 8.0))
        ds = arc_len / steps
        dtheta = sign * angle_rad / steps
        for _ in range(steps):
            heading += dtheta
            x += ds * math.cos(heading)
            y += ds * math.sin(heading)
            points.append((x, y))

    def add_hairpin(radius: float):
        # Tight ~180-200 degree turn with short entry/exit
        sign = rng.choice([1, -1])
        add_straight(0.25 * straight_length)
        add_arc(radius * rng.uniform(0.85, 1.15), rng.uniform(170, 210), direction=sign)
        add_straight(0.25 * straight_length)

    def add_sweeper(radius: float):
        # Long gentle arc
        sign = rng.choice([1, -1])
        add_arc(radius * rng.uniform(0.9, 1.2), rng.uniform(60, 140), direction=sign)

    def add_chicane(offset: float, length: float):
        # Quick left-right-left (or mirrored) with short straight
        sign = rng.choice([1, -1])  # orientation
        r1 = max(40.0, offset * rng.uniform(0.7, 1.1))
        r2 = max(40.0, offset * rng.uniform(0.6, 0.9))
        add_arc(r1, 35, direction=sign)
        add_arc(r2, 70, direction=-sign)
        add_arc(r1, 35, direction=sign)
        add_straight(0.2 * length)

    def add_s_curve(radius: float, length: float):
        # Two moderate opposite arcs with short straight between
        sign = rng.choice([1, -1])
        add_arc(radius * rng.uniform(0.9, 1.2), rng.uniform(35, 60), direction=sign)
        add_straight(0.25 * length)
        add_arc(radius * rng.uniform(0.9, 1.2), rng.uniform(35, 60), direction=-sign)
        add_straight(0.25 * length)

    # --- new: utilities to close, smooth, and resample the loop ---

    def _wrap_angle(a: float) -> float:
        return (a + math.pi) % (2.0 * math.pi) - math.pi

    def _clamp(v: float, lo: float, hi: float) -> float:
        return max(lo, min(hi, v))

    def close_loop(target_xy: tuple[float, float], turn_radius: float, step: float = 8.0, max_steps: int = 6000):
        """Bring the current turtle (x,y,heading) back to target with bounded curvature."""
        nonlocal x, y, heading
        turn_radius = max(30.0, float(turn_radius))
        ds = float(step)
        dtheta_max = ds / turn_radius  # curvature limit
        for _ in range(max_steps):
            dx = target_xy[0] - x
            dy = target_xy[1] - y
            dist = math.hypot(dx, dy)
            if dist <= ds:
                break
            desired = math.atan2(dy, dx)
            ang_diff = _wrap_angle(desired - heading)
            heading += _clamp(ang_diff, -dtheta_max, dtheta_max)
            x += ds * math.cos(heading)
            y += ds * math.sin(heading)
            points.append((x, y))
        # snap final point to exact start to make a proper loop
        points.append((target_xy[0], target_xy[1]))

    def chaikin_smooth_closed(pts: list[tuple[float, float]], iterations: int = 2) -> list[tuple[float, float]]:
        """Corner-cutting smoother for closed polylines; preserves loop but removes spikes."""
        if len(pts) < 3:
            return pts[:]
        out = pts[:]
        for _ in range(max(0, iterations)):
            new_pts = []
            n = len(out)
            for i in range(n):
                p0 = out[i]
                p1 = out[(i + 1) % n]
                qx = 0.75 * p0[0] + 0.25 * p1[0]
                qy = 0.75 * p0[1] + 0.25 * p1[1]
                rx = 0.25 * p0[0] + 0.75 * p1[0]
                ry = 0.25 * p0[1] + 0.75 * p1[1]
                new_pts.append((qx, qy))
                new_pts.append((rx, ry))
            out = new_pts
        return out

    def resample_closed(pts: list[tuple[float, float]], spacing: float) -> list[tuple[float, float]]:
        """Uniformly resample a closed polyline to roughly equal spacing."""
        if len(pts) < 2:
            return pts[:]
        # edge list includes last->first to treat closed loop
        edges = []
        total = 0.0
        for i in range(len(pts)):
            a = pts[i]
            b = pts[(i + 1) % len(pts)]
            dx, dy = b[0] - a[0], b[1] - a[1]
            L = math.hypot(dx, dy)
            edges.append((a, b, L))
            total += L
        if total < 1e-6:
            return pts[:]
        n_samples = max(8, int(total / max(1e-6, spacing)))
        # walk edges accumulating samples
        samples = []
        d = 0.0
        edge_idx = 0
        a, b, L = edges[0]
        while len(samples) < n_samples:
            t = d / L if L > 0 else 1.0
            t = _clamp(t, 0.0, 1.0)
            x_s = a[0] + (b[0] - a[0]) * t
            y_s = a[1] + (b[1] - a[1]) * t
            samples.append((x_s, y_s))
            d += total / n_samples
            while d > L and edge_idx < len(edges) - 1:
                d -= L
                edge_idx += 1
                a, b, L = edges[edge_idx]
        return samples

    # Build the segment plan
    feature_list: list[str] = []
    feature_list += ['straight'] * max(0, int(straights))
    feature_list += ['hairpin'] * max(0, int(hairpins))
    feature_list += ['chicane'] * max(0, int(chicanes))
    feature_list += ['sweeper'] * max(0, int(sweepers))
    feature_list += ['s_curve'] * max(0, int(s_curves))
    feature_list = feature_list * max(1, int(laps))
    rng.shuffle(feature_list)

    # Optionally bias the overall path to wrap around using a few sweepers if empty
    if not feature_list:
        feature_list = ['sweeper'] * 4 + ['straight'] * 2

    # Generate segments
    for feat in feature_list:
        if feat == 'straight':
            add_straight(straight_length * rng.uniform(0.8, 1.3))
        elif feat == 'hairpin':
            add_hairpin(hairpin_radius * rng.uniform(0.8, 1.2))
        elif feat == 'chicane':
            add_chicane(chicane_offset, 0.6 * straight_length)
        elif feat == 'sweeper':
            add_sweeper(sweeper_radius * rng.uniform(0.9, 1.3))
        elif feat == 's_curve':
            add_s_curve(sweeper_radius * rng.uniform(0.7, 1.0), 0.6 * straight_length)

        # Add occasional small jitter arc or straight to increase complexity
        if rng.random() < 0.3:
            add_arc(base_radius * rng.uniform(0.4, 1.2), rng.uniform(10, 25), direction=rng.choice([1, -1]))
        if rng.random() < 0.25:
            add_straight(rng.uniform(80, 180))

    # --- new: close the loop smoothly, then smooth and resample to avoid backtracking ---
    start_xy = points[0]
    close_loop(start_xy, turn_radius=sweeper_radius)  # curvature-limited closure
    points = chaikin_smooth_closed(points, iterations=2)
    points = resample_closed(points, spacing=8.0)

    # Center and scale to screen bounds
    min_x = min(p[0] for p in points)
    max_x = max(p[0] for p in points)
    min_y = min(p[1] for p in points)
    max_y = max(p[1] for p in points)
    w = max(1.0, max_x - min_x)
    h = max(1.0, max_y - min_y)

    # Margin so walls fit on screen
    margin = 160.0 + track_width
    scale = min((WIDTH - margin) / w, (HEIGHT - margin) / h)
    cx_src = 0.5 * (min_x + max_x)
    cy_src = 0.5 * (min_y + max_y)
    cx_dst, cy_dst = WIDTH / 2.0, HEIGHT / 2.0

    scaled_points = [((px - cx_src) * scale + cx_dst, (py - cy_src) * scale + cy_dst) for (px, py) in points]

    return Track(scaled_points, track_width)

def main():
    pygame.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption("Track & Car Visualization")
    clock = pygame.time.Clock()

    track = create_track()  # e.g., create_track(straights=4, hairpins=2, chicanes=2, sweepers=4, s_curves=2, laps=1, seed=42)
    start_pos = track.center_points[10]
    car = Car(start_pos, turning_circle=0.4)  # Adjust turning_circle as needed

    running = True
    while running:
        keys_pressed = pygame.key.get_pressed()
        keys = {
            'W': keys_pressed[pygame.K_w],
            'A': keys_pressed[pygame.K_a],
            'S': keys_pressed[pygame.K_s],
            'D': keys_pressed[pygame.K_d]
        }
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        car.update(keys, track)

        screen.fill(WHITE)
        track.draw(screen, COLORS)
        car.draw(screen, COLORS)
        pygame.display.flip()
        clock.tick(60)

    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    main()
